### ISSUE TITLE
do we use dcat:mediaType or dct:format? class dcat:Distribution

### ISSUE THREAD

**Issue by brunasv** [Health-RI/health-ri-metadata#10]
- [ ] Hans: My preference from a technical perspective would be media type (mime type), otherwise, it would become too broad. Because format can accommodate both standardized and non-standardized format identifiers. Also both possible? 

- [x] Dena: I am not sure which one is better. In the documentation of dcat is noted that dct:mediaType is subProperty of dct:format. And it seems there is a constraint in its use, depending on if the mediatype is defined in IANA, otherwise dct:format must be used with different values. please check [https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_media_type]

**Comment by denatahvildari** [comment]
dcat:mediaType is what we agreed on, given the fact that the mediaType is within the vocabulary define in IANA. https://www.iana.org/assignments/media-types/media-types.xhtml
