### ISSUE TITLE
VCARD shapes are not entirely to spec

### ISSUE THREAD

**Issue by Markus92** [Health-RI/health-ri-metadata#113]
While working on SeMPyRO, I've discovered some potential errors in the vcard shapes like they are enforced for dataset.
The shape expect it to be a `vcard:Kind` and the name of the thing in the vcard to be `vcard:hasName`.

However, the specification and official examples are a bit different: https://www.w3.org/submissions/vcard-rdf/#Class
Specifically, they mention a vcard may be a `vcard:VCard` and the `kind` is a placeholder for e.g. organization, individual etc.: the kind of thing the vcard is referring to.
They also mention that `fn` is the _only_ mandatory property. In the spec about hasName it looks like it has to do more with specifying the components the name has.

Could y'all please look into this? Thanks!

**Comment by Markus92** [comment]
Discussed today with Bruna, Hannah, XiaoFeng and me: the SHACL came from FDP specs and was wrong. We will fix them to conform to

**Comment by Markus92** [comment]
Latest version of the VCARD RDF ontology: https://www.w3.org/TR/vcard-rdf/

**Comment by xiaofengleo** [comment]
This was discussed in Jira ticket https://health-ri.atlassian.net/jira/software/c/projects/SRP/boards/5?selectedIssue=SRP-541, and resolved in pull request https://github.com/Health-RI/health-ri-metadata/pull/123

**Comment by kburger** [comment]
Closed by #123 and #124.
