### ISSUE TITLE
What is the semantic relation between Study, Project

### ISSUE THREAD

**Issue by denatahvildari** [Health-RI/health-ri-metadata#12]
In a review session with Bruna, we discussed that we need to have a more clear definition of `hri:Study` and `dcat:Project` and understand their relation.  

Some facts:
- In the current model, they are related through the class `dcat:Dataset`. 
- They share some datatype properties but `hri:Study` will have its own attributes. 
- Can we reuse `isa:Study`, instead of `hri:Study`?  According to the **ISA** model: https://isa-specs.readthedocs.io/en/latest/isamodel.html
  - `Study` `isPartOf` an  `Investigation `; and 
  - `Assay` `isPartOf` an `Study`;
  - `Study` `hasdata` `Dataset` 
  - `Study` `hasMeasurement` `Measurement`

**Comment by denatahvildari** [comment]
- check with nodes? Imaging, Omics, biobank
- check for what are the portal requirement from user perspective? Do users search/filter on Study to get to the datasets?

**Comment by konradana** [comment]
Added to the backlog for future modeling.

**Comment by brunasv** [comment]
#20 https://github.com/Health-RI/health-ri-metadata/issues/20

**Comment by konradana** [comment]
Project and Study have been added to the new version of the model, which is currently in pre-release. Documentation about it can be found in the `develop` branch.
