### ISSUE TITLE
dcat:modified cardinality wrong in SHACL

### ISSUE THREAD

**Issue by Markus92** [Health-RI/health-ri-metadata#131]
When updating img2catalog, I noticed the SHACLs for Dataset do not mandate dcat:modified. Reason is that the maxCount is 1, but the minCount field is not present (thus making it optional).
The specification says it should be mandatory, the SHACLs should be updated to reflect this.

**Comment by xiaofengleo** [comment]
fixed in pr 132, https://github.com/Health-RI/health-ri-metadata/pull/132
