### ISSUE TITLE
License not mandatory in release v1.0.0 dataset SHACL

### ISSUE THREAD

**Issue by KarolisCremers** [Health-RI/health-ri-metadata#134]
https://github.com/Health-RI/health-ri-metadata/blob/708442b671b276c05b2ea35c0b50e84ca6f9062d/Formalisation(shacl)/Core/PiecesShape/Dataset.ttl#L62-L68

reference UML diagram:
https://github.com/Health-RI/health-ri-metadata/blob/v1.0.0/Images/1.0_plateau1/HRICoreSchemaReleasePlateau1.jpg

Solution:
Add
`sh:minCount 1 ;`
to the contstraints for this path

**Comment by xiaofengleo** [comment]
addressed in this pr, https://github.com/Health-RI/health-ri-metadata/pull/132
