### ISSUE TITLE
Modified not mandatory in release 1.0.0 dataset SHACL

### ISSUE THREAD

**Issue by KarolisCremers** [Health-RI/health-ri-metadata#135]
https://github.com/Health-RI/health-ri-metadata/blob/708442b671b276c05b2ea35c0b50e84ca6f9062d/Formalisation(shacl)/Core/PiecesShape/Dataset.ttl#L69-L75

Reference UML diagram:
https://github.com/Health-RI/health-ri-metadata/blob/develop/Images/1.0_plateau1/HRICoreSchemaReleasePlateau1.jpg

Solution:
Add
`sh:minCount 1 ;`
to the contraints for this path

**Comment by Markus92** [comment]
Duplicate of https://github.com/Health-RI/health-ri-metadata/issues/131
