### ISSUE TITLE
File with that should resolve all found mandatory issues with v1.0.0 dataset SHACL

### ISSUE THREAD

**Issue by KarolisCremers** [Health-RI/health-ri-metadata#137]
#133 #134 #135 #136 

File (txt because github doesn't like ttl) with solutions added for issues #133 #134 #135 #136 :
[dataset.txt](https://github.com/user-attachments/files/16508915/dataset.txt)

**Comment by xiaofengleo** [comment]
addressed in this pr, https://github.com/Health-RI/health-ri-metadata/pull/132
