### ISSUE TITLE
feedback: Catalogued Resource mandatory classes

### ISSUE THREAD

**Issue by jundahuang9123** [Health-RI/health-ri-metadata#152]
### Version check

- [X] My issue concerns the draft v2 model

### Duplicate check

- [X] I have searched both open and closed issues and found no similar reports.

### Class and property

Catalogued Resource

### Issue description

Catalogued Resource is a mandatory class, but it is stated that it is not being used. It is not described in UML diagram. This is confusing and need to clarification

### Proposed change

It concerns high level grouping, which is not mapped with intentions from the users' prospective. Maybe drop it form mandatory or from the overview entirely.

### Priority

Nice to have

**Comment by HNeikes** [comment]
These abstract classes are now hidden in the latest documentation (pre-release of v2 model).
