### ISSUE TITLE
feedback: dataset property within Catalog

### ISSUE THREAD

**Issue by jundahuang9123** [Health-RI/health-ri-metadata#153]
### Version check

- [X] My issue concerns the draft v2 model

### Duplicate check

- [X] I have searched both open and closed issues and found no similar reports.

### Class and property

Catalog Class dataset property

### Issue description

Both classes Catalog and Dataset are mandatory classes, doesnt it make the property dataset within class Catalog mandatory (it is now recommended)?

### Proposed change

I would think Dataset class not mandatory since it can be empty during development phase.

### Priority

Must have

**Comment by HNeikes** [comment]
Compliant to DCAT-AP NL [specifications](https://geonovum.github.io/DCAT-AP-NL30/#catalog-dcat-catalog) and [shacls](https://geonovum.github.io/DCAT-AP-NL30/shapes/dcat-ap-nl-SHACL.ttl), the Dataset property in Catalogue and the Dataset class itself are now mandatory.
