### ISSUE TITLE
feedback: ORCID for creator

### ISSUE THREAD

**Issue by aframosp** [Health-RI/health-ri-metadata#155]
### Version check

- [X] My issue concerns the draft v2 model

### Duplicate check

- [X] I have searched both open and closed issues and found no similar reports.

### Class and property

Property creator

### Issue description

The creator in a dataset should be identifiable through a unique identifier, similar to how publishers are identified using the Research Organization Registry (ROR). In the context of research, the Open Researcher and Contributor ID (ORCID) is the most suitable option for this purpose. Maybe this just need to be explicitly mentioned in the example column.

### Proposed change

Add the option of having an identifier (ORCID) in the creator property

### Priority

Should have

**Comment by jundahuang9123** [comment]
Creator has the range of foaf:Agent can be person or organization.Agent class contain property id (orcid or ROR).
