### ISSUE TITLE
feedback: Licenses identifiers

### ISSUE THREAD

**Issue by aframosp** [Health-RI/health-ri-metadata#156]
### Version check

- [X] My issue concerns the draft v2 model

### Duplicate check

- [X] I have searched both open and closed issues and found no similar reports.

### Class and property

Property license

### Issue description

In the property of license there is no example in that column. It would be helpful to specify which value list should be used when a dataset is openly available. For example, use the [list of licenses of SPDX](https://spdx.org/licenses/) for names and identifiers. 

### Proposed change

When a license is added, give the possibility that an (SPDX) identifier is also added 

### Priority

Should have

**Comment by HNeikes** [comment]
For now, we have added a recommendation to the latest documentation to use one of the licences provided by [DCAT-AP NL](https://definities.geostandaarden.nl/dcat-ap-nl/nl/). In case of non-open data, further specifications for reuse of data should be provided in the dct;rights property.
