### ISSUE TITLE
feedback: Study object

### ISSUE THREAD

**Issue by agjharms** [Health-RI/health-ri-metadata#162]
### Version check

- [X] My issue concerns the draft v2 model

### Duplicate check

- [X] I have searched both open and closed issues and found no similar reports.

### Class and property

Class: Study

### Issue description

I was wondering how you envision the Study concept to be used. During a discussion on modeling imaging data the question came up if for example a scanning technique (e.g., a T1-weighted MRI scan with certain parameters) or another data acquisition method can/should be modeled as a Study in this framework. Is this the case or is a Study a broader description of the organization of data collection? 

### Proposed change

It would be nice to have a more concrete description, or an example, of how to use the Study object.

### Priority

Nice to have

**Comment by HNeikes** [comment]
The study class is indeed intended to provide information about data generation/collection. The organizational aspects should be provided in the project class. However, both project and study currently contain a minimal number of properties. The proposed properties, cardinalities and ranges are a starting point, and should be further developed next year.
