### ISSUE TITLE
Re-evaluating Ontology Visualization Tools: Visual Paradigm vs. specialised ontology editing and visualisating tools (e.g. Metaphacts)

### ISSUE THREAD

**Issue by denatahvildari** [Health-RI/health-ri-metadata#19]
Issue:

After an some time working with visualization capabilities provided by Visual Paradigm, I've identified a few shortcomings when it comes to accurately and efficiently representing ontological relationships and data structures.

Reasons for Concern:

Complexity: Visual Paradigm, while a robust UML and modeling tool, is not natively tailored for ontology viewing. This might lead to an over-complication of the visualisation or omission of critical ontology-specific details.

Limited Customizability: The ontology viewing options and customisability in Visual Paradigm are not as extensive as other specialised tools, making it difficult to adapt to specific ontology visualisation needs.

Integration with other Semantic Web tools: Visual Paradigm may not easily integrate with other Semantic Web tools, which can be a bottleneck for ontology-based projects.

Suggested Alternative: Metaphactory:

After some research and also having worked with the tool, I believe Metaphactory is a more suitable option for our ontology visualization needs for several reasons:

Purpose-built: Unlike Visual Paradigm, Metaphactory is designed specifically for working with ontologies, ensuring a more intuitive and comprehensive visualization experience.

Flexibility: It offers a range of customizable visualization options tailored to ontology structures.

Integration: Metaphactory provides smoother integration with other Semantic Web tools, making it more adaptable for our workflow.

and it is not complicated for the non semantic technical users. 

To provide a clearer picture, I propose setting up a call/demo with Metaphactory. This will help us assess its capabilities firsthand and determine if it's a better fit for our requirements.

I believe that transitioning to a more tailored tool will streamline our ontology visualisation processes and lead to better outcomes in our projects.

**Comment by denatahvildari** [comment]
will be discussed with bruna, luiz, kess, and other people from implemtation team.

**Comment by konradana** [comment]
Closing this issue since the continuation of it was moved to the internal Jira board [here](https://health-ri.atlassian.net/browse/DATA-12). The issue itself has not been resolved yet.
