### ISSUE TITLE
dcat:distribution description mandatory?

### ISSUE THREAD

**Issue by Markus92** [Health-RI/health-ri-metadata#26]
Hi,
I see for a description that distribution is mandatory, just wondering what am I supposed to fill in there?
There's no example and it's not mandatory in DCAT-AP so no reference there either.
Any chance this is an oversight? As it is mandatory for dcat:dataset and dcat:catalogue
Note: same applies to "title".
Thanks,
Mark

**Comment by konradana** [comment]
Distribution is not mandatory, but in case it is added, description of it is mandatory.
