### ISSUE TITLE
foaf:Agent definition and foam:Agent vs vCard usage

### ISSUE THREAD

**Issue by a-nayden** [Health-RI/health-ri-metadata#33]
1. A recommended range for `dcat:ContactPoint` is `vCard:Kind` while HRI model uses `foaf:Agent` is there a reason for this?

2. HRI definition of Agent includes two properties `name` and `identifier`. `name` is a part of FOAF core and not included to `foaf:Agent` by definition (http://xmlns.com/foaf/spec/#term_Agent) and `identifier` is `dcterms:identifier` (also not among properties). How the choice between `dcterms:identifier` and `adms:identifier` is made? Why is this object is `foaf:Agent` if it seems to be a custom type?

**Comment by denatahvildari** [comment]
We modified the range of the dcat:contactPoint to vcard:Kind.  i opened a new ticket to make clear usage note for node on how instantiate the class(vcard:Kind)
