### ISSUE TITLE
dcat.theme vs dcat.themeTaxonomy for Dataset 

### ISSUE THREAD

**Issue by a-nayden** [Health-RI/health-ri-metadata#34]
As per notation Resource has property `theme`, RDF property is `dcat.theme`.
A catalog inherits that from Resource class but has a property of its own `themes`, corresponding RXF property is `dcat.themeTaxonomy`.  Shouldn't URI for HRI model `Dataset.theme` be `dcat.theme` instead of `dcat.themeTaxonomy`?

**Comment by denatahvildari** [comment]
dct:theme is a object prperty linking class(dcat:Dataset) to it taxonomy in skos:themeScheme which is skos:ConceptScheme

**Comment by denatahvildari** [comment]
I corrected the sh:path
