### ISSUE TITLE
Core: dct:relation in a dataset; mandatory or recommended

### ISSUE THREAD

**Issue by agjharms** [Health-RI/health-ri-metadata#35]
Hi all,

Currently for the Dataset concept the attribute dct:relation is marked as mandatory. Since there might be a number of people uploading a single dataset, or a first dataset with related datasets in the future, which would not have a relation at the time of uploading, I can see that this might be confusing for these people. They would be blocked from adding their dataset to the catalogue for, in their eyes, the an understandable reason. I understood from a conversation with Dena that making dct:relation mandatory was a choice to get data uploaders to provide as much context as possible. While I fully agree with that goal, for the reasons above it might be good to look at making dct:relation recommended instead of mandatory. 

Additionally, I see that the range for 'relation' is marked as 'foaf:Project', while there is also a separate attribute 'project' for the Dataset concept. I don't know if this is intentional, but could dct:relation also benefit from a broader range?

**Comment by denatahvildari** [comment]
The initial rational for the usage of this predicate was for linking Dataset to Project. We reused the generic dct:relation predicate to avoid defining a new objectProperty. 

The point is taken the predicate needs to become more explicit and it should categorised as a recommended relation.
