### ISSUE TITLE
[core shapes] dcat namespace is incorrect

### ISSUE THREAD

**Issue by kburger** [Health-RI/health-ri-metadata#36]
https://github.com/Health-RI/health-ri-metadata/blob/4cd351a9e6c178c64e92413a188c14a6652c1061/Metadata%20Schemas%20(Formal%20models)/Core%20Metadata%20Model/core.shapes.ttl#L15

The correct namespace for dcat is `http://www.w3.org/ns/dcat#`

**Comment by denatahvildari** [comment]
@kburger the name space  is automatically extracted with the import feature on topbraid. The import feature of topbraid allows you to bring the ttl which is on the web https://www.w3.org/ns/dcat.ttl

which I got referenced from the specification sheet. 

https://github.com/Health-RI/health-ri-metadata/blob/master/Metadata%20Schemas%20(Formal%20models)/Core%20Metadata%20Model/core.shapes.ttl
