### ISSUE TITLE
[core shapes] consistent use of PropertyShape typing

### ISSUE THREAD

**Issue by kburger** [Health-RI/health-ri-metadata#39]
https://github.com/Health-RI/health-ri-metadata/blob/4cd351a9e6c178c64e92413a188c14a6652c1061/Metadata%20Schemas%20(Formal%20models)/Core%20Metadata%20Model/core.shapes.ttl#L224-L232

The majority of the property definitions do not have an explicit type set. Let's make a decision on explicit or implicit types.

**Comment by denatahvildari** [comment]
addressed
