### ISSUE TITLE
[core shapes] use of non-spec constraint `sh:shape`

### ISSUE THREAD

**Issue by kburger** [Health-RI/health-ri-metadata#40]
https://github.com/Health-RI/health-ri-metadata/blob/4cd351a9e6c178c64e92413a188c14a6652c1061/Metadata%20Schemas%20(Formal%20models)/Core%20Metadata%20Model/core.shapes.ttl#L257-L269

`sh:shape` does not existi in the SHACL specification; this should probably be `sh:node`? Or is this a custom topbraid extension?

**Comment by denatahvildari** [comment]
- sh:Shape is the [SHACL superclass](https://www.w3.org/TR/shacl/#dfn-shacl-superclass) of those two shape types in the SHACL vocabulary. Its subclasses sh:NodeShape and sh:PropertyShape can be used as SHACL type of node and property shapes, respectively.
- Also Topbraid composer allows its usage. 
- i understand the problem. I probably made a core node at some point to be reused but it is not needed as the datetime constraint can be defined with the datatype only -- 
- I will correct it for this sh:shape core:DateOrDateTimeDataType_Shape ;
