### ISSUE TITLE
[core shapes] extend decimal property constraints

### ISSUE THREAD

**Issue by kburger** [Health-RI/health-ri-metadata#41]
https://github.com/Health-RI/health-ri-metadata/blob/4cd351a9e6c178c64e92413a188c14a6652c1061/Metadata%20Schemas%20(Formal%20models)/Core%20Metadata%20Model/core.shapes.ttl#L286-L290

This could use more strict constraints from the value range constraints, like min ex/inclusive. Does topbraid allow for these definitions?

**Comment by denatahvildari** [comment]
We do not model the resolution in this version. So i removed the statement.
