### ISSUE TITLE
[core shapes] catalog shape defines too strict constraints on its dataset property

### ISSUE THREAD

**Issue by kburger** [Health-RI/health-ri-metadata#44]
https://github.com/Health-RI/health-ri-metadata/blob/4cd351a9e6c178c64e92413a188c14a6652c1061/Metadata%20Schemas%20(Formal%20models)/Core%20Metadata%20Model/core.shapes.ttl#L124-L129

We cannot make an empty catalog using this definition.

**Comment by denatahvildari** [comment]
Yes cardinality changed to 0
