### ISSUE TITLE
[UsageNote] Not clear how vcard is going to be instantiated.

### ISSUE THREAD

**Issue by denatahvildari** [Health-RI/health-ri-metadata#48]
We deciede to define a vcard:Kind for dcat:contactPoint. 

Which field in Kind should be instantiated? 
example is needed to become clear for the community

**Comment by denatahvildari** [comment]
which attributes from vcard:Kind do we expect to be instantiated from nodes.

**Comment by KarolisCremers** [comment]
Has there been any progress on this?

**Comment by PatrickDekkerHealthRI** [comment]
The old file corerules.shapes.ttl is outdated and will be removed soon, please use the newer shapes.

[https://github.com/Health-RI/health-ri-metadata/tree/master/Formalisation(shacl)/Core/PiecesShape](url)
