### ISSUE TITLE
[core shapes] `sh:uniqueLang` seems to be repeated for all shapes

### ISSUE THREAD

**Issue by kburger** [Health-RI/health-ri-metadata#51]
https://github.com/Health-RI/health-ri-metadata/blob/c4648a69ac6cf660515808f7321ec2d706509a97/Foraml%20Models%20(shapes%2C%20rdf%2C%20skos%2C)/Core%20Metadata%20Module/coreRules.shapes.ttl#L37C13-L37C31

it seems like every single property shape now has a `sh:uniqueLang` constraint, even the non-literal typed ones.

**Comment by denatahvildari** [comment]
correct - only defined for the nodekind literal
