### ISSUE TITLE
[core shapes] dash viewer and editor decisions

### ISSUE THREAD

**Issue by kburger** [Health-RI/health-ri-metadata#52]
https://github.com/Health-RI/health-ri-metadata/blob/c4648a69ac6cf660515808f7321ec2d706509a97/Foraml%20Models%20(shapes%2C%20rdf%2C%20skos%2C)/Core%20Metadata%20Module/coreRules.shapes.ttl#L101-L102

In this example, the `dash:viewer` is `dash:LabelViewer`, where the intention behind the property is the URL address, assuming it is pointing to a "regular" document and not a concept. In this case the user would expect to see the URL, and not a maybe-or-maybe-not resolved label for it.

(maybe this can be an aggregate issue for collecting dash decisions)

**Comment by PatrickDekkerHealthRI** [comment]
We went thru all the shacl's and updated to dash viewers and editor when needed. 

see: https://github.com/Health-RI/health-ri-metadata/pull/84
