### ISSUE TITLE
Range for some properties

### ISSUE THREAD

**Issue by a-nayden** [Health-RI/health-ri-metadata#54]
- `Catalog.description` and `Dataset.description` are inherited from Resource properties - why different range then? If there is no reason to override, both should be union of rdfs:Literal and xsd:string to allow languages
- `Dataset.identifier` - shouldn't be rdfs:literal to allow xsd:token or a union of xsd:string and xsd: token?
- `Dataset.has_version` - should be an IRI by definition
- `DataService.endPointDescription` - range should be extended with IRI as per definition if a link for a document is expected
- `Distribution.accessURL` and `downloadURL` - URL is an IRI, not a string
- `Distribution.media type` - an IRI as long as it is a reference to IANA
- `Distribution.title` and `Distribution.description` - shouldn't both be redfs:literal to allow languages?
-`Project.description/title` - shouldn't both be rdsf:literal for languages and to be consitent with Resource
- `Project.identifier` - shouldn't be rdfs:literal to allow xsd:token or a union of xsd:string and xsd:token?

**Comment by denatahvildari** [comment]
please check the refine diagram here: https://github.com/Health-RI/health-ri-metadata/blob/master/Diagrams%20(Visual%20Paradigm)/Plateau%201%20-%20Core%20schema%20Conceptual%20model/CoreModelImage.png
to access it in visual paradigm here: https://github.com/Health-RI/health-ri-metadata/blob/master/Diagrams%20(Visual%20Paradigm)/Plateau%201%20-%20Core%20schema%20Conceptual%20model/coreMedataSchemaRefinedP1.vpp
the updates on shapes as well are here: https://github.com/Health-RI/health-ri-metadata/blob/master/Foraml%20Models%20(shapes%2C%20rdf%2C%20skos%2C)/Core%20Metadata%20Module/coreRules.shapes.ttl

- why version should be an IRI?
- Distribution.title and Distribution.description: xsd:String also allows for different languages, but sure if it helps covering other input i change it to rdfs:Literal.

**Comment by a-nayden** [comment]
in DCAT v3 there is a difference between `version` and `hasVersion` - first one is a literal version and can be expressed as a string and `hasVersion` is an equivalent of `pav:hasVersion` and is used to link a resource to its versions, so the range is Resource or IRI (to the previous version of the resource)

As for title and description would be nice to have refs:literal so we can have a value with language information stored as a label. That is how FDP works currently.
