### ISSUE TITLE
FDP

### ISSUE THREAD

**Issue by priya-gitTest** [Health-RI/health-ri-metadata#68]
Hi,

apologies in advance for writing this here. I want to replicate the installation of FDP server and client.
https://health-ri.atlassian.net/wiki/spaces/FSD/pages/293109770/3.c+FDP+in+a+box
Unfortunately, its not clear what kind of machine is needed. 
If I understand a Linux might work well with Docker but which distro of Linux then ? e.g. Debian or CentOS ?

Priyanka

**Comment by Markus92** [comment]
We tested on macOS and Ubuntu, but Debian / CentOS should work well, too.
