### ISSUE TITLE
Core rule change

### ISSUE THREAD

**Issue by KarolisCremers** [Health-RI/health-ri-metadata#74]
https://github.com/Health-RI/health-ri-metadata/blob/88009525aeff489817fe901454a381b0642a8504/Formalisation(shacl)/Core/coreRules.shapes.ttl#L33

should be http://xmlns.com/foaf/0.1/name according to:
[Images/1.0_plateau1/HRICoreSchemaReleasePlateau1.jpg](https://github.com/Health-RI/health-ri-metadata/blob/master/Images/1.0_plateau1/HRICoreSchemaReleasePlateau1.jpg)

If I'm understanding the core rules incorrectly and it should be a title please let me know.

I also would like to be informed whether the agent shape:
https://github.com/Health-RI/health-ri-metadata/blob/88009525aeff489817fe901454a381b0642a8504/Formalisation(shacl)/Core/PiecesShape/Catalog.ttl#L54-L63
in the catalog shape file is inheriting the property requirements from the ontology.

**Comment by brunasv** [comment]
Here are the latest shapes https://github.com/Health-RI/health-ri-metadata/tree/master/Formalisation(shacl)/Core/PiecesShape

**Comment by brunasv** [comment]
Hi Karolis, Can you point me to " property requirements from the ontology." , thanks!

**Comment by KarolisCremers** [comment]
> Hi Karolis, Can you point me to " property requirements from the ontology." , thanks!
As defined at the top of the file:
https://github.com/Health-RI/health-ri-metadata/blob/9621c21281354fbfab321b95ab8343cd67229332/Formalisation(shacl)/Core/coreRules.shapes.ttl#L18-L27

The definitions that follow indicate which fundemental requirements are to be followed to onboard metadata. 
I interpret this in a way that any class property defined in this file have to be present in any of its uses and that the seperate shapes extend the property requirements.

The ontology in the following file defines an agent shape in this way:
https://github.com/Health-RI/health-ri-metadata/blob/9621c21281354fbfab321b95ab8343cd67229332/Formalisation(shacl)/Core/coreRules.shapes.ttl#L29-L45

So am I correct in thinking that all agents across the shapes should have a dc:title and dc:identifier (as sh:mincCount = 1)? And that the agent associated to "publisher" for a catalog has an additional property requirement of foaf:name?:
https://github.com/Health-RI/health-ri-metadata/blob/9621c21281354fbfab321b95ab8343cd67229332/Formalisation(shacl)/Core/PiecesShape/Catalog.ttl#L53-L63

I'm assuming that the CoreRules.shapes.ttl and PiecesShape SHACL files are related to each-other.

Hope this helps, I'm not entirely sure if I'm using the correct language so sorry for the confusion in advance.

**Comment by brunasv** [comment]
no problem, @xiaofengleo  can you help here? (Also the pieces shapre is the correct shacl, we are cleaning the git, sorry for the confusion)

**Comment by xiaofengleo** [comment]
The CoreRules.shapes.ttl mentioned is removed since split the shapes into each class corresponding to the core metadata diagram. According to the diagram, the foaf:agent only contains foaf:name and dct:identifier.

**Comment by brunasv** [comment]
XiaoFeng, maybe point the link to the correct shapes once more, and then I think we can close the issue (if @KarolisCremers agrees).

**Comment by KarolisCremers** [comment]
Sounds good to me!
