### ISSUE TITLE
Double path in Catalog shape property

### ISSUE THREAD

**Issue by KarolisCremers** [Health-RI/health-ri-metadata#75]
https://github.com/Health-RI/health-ri-metadata/blob/9621c21281354fbfab321b95ab8343cd67229332/Formalisation(shacl)/Core/PiecesShape/Catalog.ttl#L30-L34

**Comment by brunasv** [comment]
@Markus92 please note this, not sure if its fixed in the latest validator.

**Comment by Markus92** [comment]
@brunasv please make a PR in that repository once it's updated
