### ISSUE TITLE
Duplicate namespace

### ISSUE THREAD

**Issue by KarolisCremers** [Health-RI/health-ri-metadata#76]
https://github.com/Health-RI/health-ri-metadata/blob/9621c21281354fbfab321b95ab8343cd67229332/Formalisation(shacl)/Core/coreRules.shapes.ttl#L14-L15

**Comment by xiaofengleo** [comment]
@KarolisCremers This was deprecated. Please see https://github.com/Health-RI/health-ri-metadata/tree/master/Formalisation(shacl)/Core/PiecesShape for the schal shapes for core metadata model in plateau 1.
