### ISSUE TITLE
What are the leading specifications?

### ISSUE THREAD

**Issue by KarolisCremers** [Health-RI/health-ri-metadata#77]
https://health-ri.atlassian.net/wiki/spaces/FSD/pages/121110529/Core+Metadata+Schema+Specification
or
The SHACL shapes: (https://github.com/Health-RI/health-ri-metadata/tree/master/Formalisation(shacl)/Core/PiecesShape)
or
The core rules ontology: (https://github.com/Health-RI/health-ri-metadata/blob/master/Formalisation(shacl)/Core/coreRules.shapes.ttl)

These files are inconsistent with each-other, I'm assuming it is the wiki, but if there is another I'm fine using it as a base for our onboarding ETL pipeline.

**Comment by konradana** [comment]
Yes, the [wiki page](https://health-ri.atlassian.net/wiki/spaces/FSD/pages/121110529/Core+Metadata+Schema+Specification) is the one that is most up to date, so please follow that. The [SHACL shapes](https://github.com/Health-RI/health-ri-metadata/tree/master/Formalisation(shacl)/Core/PiecesShape) should also be following the current schema.
