### ISSUE TITLE
do we use dct:type or hri:datatype? class dcat:Dataset

### ISSUE THREAD

**Issue by brunasv** [Health-RI/health-ri-metadata#9]
- [ ] Dena: I am wondering about hri: namespace. Maybe as a to do for next step, it can be good that we write down the decisions over the namespace and naming conventions and pattern for overall models. It can be valuable in the long run. 
- [ ] Jeroen:  About namespaces: preferably it should not be based on an organization if we want to apply it more broadly as in others will/want to use it too: so try to not use health-ri, so that it makes sense to the entire international space/domain/…
Before to decide we should use dcat:type or “namespace”: type -> what is the issue? Do we have an example metadata record (or a few) to make the problem clear? Is it to discriminate between different resource types, like biobank, collection, registry,..  if so then why not use dcat: Resource (is this not also done by EJP-RD?)
- [ ] Anastasia:	dct:type or hri:datatype if we use dct:type – would it be an issue for HRI/petal – specific classes? I mean are there any limits to inherit that and be consistent or we have to switch to hri:datatype then?
- [ ] Hans: Also both possible?

**Comment by denatahvildari** [comment]
health-ri agrees on the usability of dct:type to represent the type of dataset (vocabularies), however we need to check if this is a mandatory field according to do.nl  dutch government.

**Comment by denatahvildari** [comment]
follow up on #issue18
