### ISSUE TITLE
Identifier is a property of agent

### ISSUE THREAD

**Issue by KarolisCremers** [Health-RI/health-ri-metadata#95]
https://github.com/Health-RI/health-ri-metadata/blob/b39a1d78a560ac3366e0fe79812d7e3b5234d150/Formalisation(shacl)/Core/Example-Data/example-dataset.ttl#L9

This value should be added to the publisher agent node instead of being assigned to a dataset.

**Comment by xiaofengleo** [comment]
@konradana @brunasv Can you check this?

**Comment by xiaofengleo** [comment]
solved in pr https://github.com/Health-RI/health-ri-metadata/pull/105
